### ISSUE TITLE
error of ptxas fatal when install

### ISSUE THREAD

**Issue by cp3cp** [cmpute/d3d#8]
I try the command `python setup.py install` and there is a Cmake Error:
```
--------------------------------------------------------------------------------
-- Trying 'Ninja' generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.9s)
-- Generating done (0.0s)
-- Build files have been written to: /data/mengh3/CoAlign/d3d/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying 'Ninja' generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    /data/mengh3/CoAlign/d3d/_skbuild/linux-x86_64-3.7/cmake-build
  Command:
    /data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/cmake/data/bin/cmake /data/mengh3/CoAlign/d3d -G Ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/data/mengh3/CoAlign/d3d/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_VERSION_STRING:STRING=3.7.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/data/mengh3/myconda/envs/coalign/bin/python -DPYTHON_INCLUDE_DIR:PATH=/data/mengh3/myconda/envs/coalign/include/python3.7m -DPYTHON_LIBRARY:PATH=/data/mengh3/myconda/envs/coalign/lib/libpython3.7m.so -DPython_EXECUTABLE:PATH=/data/mengh3/myconda/envs/coalign/bin/python -DPython_ROOT_DIR:PATH=/data/mengh3/myconda/envs/coalign -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/data/mengh3/myconda/envs/coalign/include/python3.7m -DPython_NumPy_INCLUDE_DIRS:PATH=/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/data/mengh3/myconda/envs/coalign/bin/python -DPython3_ROOT_DIR:PATH=/data/mengh3/myconda/envs/coalign -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/data/mengh3/myconda/envs/coalign/include/python3.7m -DPython3_NumPy_INCLUDE_DIRS:PATH=/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/numpy/core/include -DBUILD_WITH_PYTORCH=ON -DCMAKE_PREFIX_PATH=/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/torch -DBUILD_WITH_CUDA=ON -DCYTHON_WITH_NO_DOCSTRINGS_ARG=FALSE -DCMAKE_BUILD_TYPE:STRING=Release

Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /data/mengh3/myconda/envs/coalign/bin/python (found version "3.7.12")
-- Found PythonLibs: /data/mengh3/myconda/envs/coalign/lib/libpython3.7m.so (found version "3.7.12")
-- Found Cython: /data/mengh3/myconda/envs/coalign/bin/cython
-- Found NumPy: /usr/include (found version "1.21.5")
CMake Error at /data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:751 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v



  The output was:

  255

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _THERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_SIZE_=64

  #$ NVVMIR_LIBRARY_DIR=/usr/lib/nvidia-cuda-toolkit/libdevice

  #$
  PATH=/usr/lib/nvidia-cuda-toolkit/bin:/data/public/CUDA11/cuda-11.2/bin:/data/mengh3/myconda/envs/coalign/bin:/data/mengh3/myconda/envs/coalign/bin:/data/mengh3/myconda/envs/coalign/bin:/data/public/CUDA11/cuda-11.0/bin:/usr/local/cuda/bin:/data/public/CUDA11/cuda-11.0/bin:/data/public/CUDA11/cuda-11.0/bin:/usr/local/cuda/bin:/data/public/CUDA11/cuda-11.0/bin:/usr/local/cuda/bin:/home/mengh3/bin:/home/mengh3/.local/bin:/usr/local/cuda/bin:/data/mengh3/myconda/envs/coalign/bin:/opt/anaconda3/condabin:/opt/anaconda3/bin:/usr/local/cuda-9.0/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin


  #$ LIBRARIES= -L/usr/lib/x86_64-linux-gnu/stubs

  #$ rm tmp/a_dlink.reg.c

  #$ gcc -std=c++14 -D__CUDA_ARCH__=300 -E -x c++
  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__
  -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1"
  -D"__CUDACC_VER_MAJOR__=9" -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii"

  #$ cicc --c++14 --gnu_version=70500 --allow_managed -arch compute_30 -m64
  -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name
  "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library
  "/usr/lib/nvidia-cuda-toolkit/libdevice/libdevice.10.bc"
  --gen_module_id_file --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name
  "CMakeCUDACompilerId.cu" --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.gpu" "tmp/CMakeCUDACompilerId.cpp1.ii" -o
  "tmp/CMakeCUDACompilerId.ptx"

  #$ ptxas -arch=sm_30 -m64 "tmp/CMakeCUDACompilerId.ptx" -o
  "tmp/CMakeCUDACompilerId.sm_30.cubin"

  ptxas fatal : Value 'sm_30' is not defined for option 'gpu-name'

  # --error 0xff --





Call Stack (most recent call first):
  /data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:309 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:14 (enable_language)


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 671, in setup
    languages=cmake_languages,
  File "/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/skbuild/cmaker.py", line 357, in configure
    raise SKBuildError(msg)

An error occurred while configuring with CMake.
  Command:
    /data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/cmake/data/bin/cmake /data/mengh3/CoAlign/d3d -G Ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/data/mengh3/CoAlign/d3d/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_VERSION_STRING:STRING=3.7.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/data/mengh3/myconda/envs/coalign/bin/python -DPYTHON_INCLUDE_DIR:PATH=/data/mengh3/myconda/envs/coalign/include/python3.7m -DPYTHON_LIBRARY:PATH=/data/mengh3/myconda/envs/coalign/lib/libpython3.7m.so -DPython_EXECUTABLE:PATH=/data/mengh3/myconda/envs/coalign/bin/python -DPython_ROOT_DIR:PATH=/data/mengh3/myconda/envs/coalign -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/data/mengh3/myconda/envs/coalign/include/python3.7m -DPython_NumPy_INCLUDE_DIRS:PATH=/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/data/mengh3/myconda/envs/coalign/bin/python -DPython3_ROOT_DIR:PATH=/data/mengh3/myconda/envs/coalign -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/data/mengh3/myconda/envs/coalign/include/python3.7m -DPython3_NumPy_INCLUDE_DIRS:PATH=/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/numpy/core/include -DBUILD_WITH_PYTORCH=ON -DCMAKE_PREFIX_PATH=/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/torch -DBUILD_WITH_CUDA=ON -DCYTHON_WITH_NO_DOCSTRINGS_ARG=FALSE -DCMAKE_BUILD_TYPE:STRING=Release
  Source directory:
    /data/mengh3/CoAlign/d3d
  Working directory:
    /data/mengh3/CoAlign/d3d/_skbuild/linux-x86_64-3.7/cmake-build
Please see CMake's output for more information.
```

**Comment by cmpute** [comment]
I haven't maintained this library for a while. I will assume that the CUDA version is not compatible with the code, or the CUDA installation has some issues.

**Comment by cmpute** [comment]
Please use alternative libraries in future, thanks.
